<div class="row">
    <div class="col-md-7">
        <h2>Cảnh báo</h2>
        <div class="alert alert-danger">
            Bạn đang truy cập vào khu vực trái phép
            <br>
            +Nếu bạn chưa đăng nhập thì hãy đăng nhập rồi truy cập lại <br>
            +Nếu đã đăng nhập mà vẫn hiện thông báo nghĩa là tài khoản của bạn chưa được cấp quyền để truy cập trang này!

        </div>
    </div>
</div>