<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2014 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Application\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;

class IndexController extends AbstractActionController
{
    public function onDispatch(MvcEvent $e)
    {
        $route = $e->getRouteMatch();
        //lấy controller
        $controller = $route->getParam('controller');
//        $moduleName =strtolower(substr($controller,0,strpos($controller,'\\')));
        $arr = explode('\\', $controller);

        $moduleName = strtolower($arr[0]);

        $this->layout()->setTemplate('layout/'.$moduleName);
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }
    public function indexAction()
    {
        return new ViewModel();
    }
}
