<?php
/**
 * Created by PhpStorm.
 * User: Thai Duc
 * Date: 28-Feb-18
 * Time: 11:49 PM
 */

namespace Training\Controller;


use Blog\Controller\MainController;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;
use Zend\View\Model\ViewModel;
use Zend\Permissions\Acl\Role\GenericRole as Role;

class AclController extends MainController
{
    public function onDispatch(MvcEvent $e)
    {
        $acl = new \Zend\Permissions\Acl\Acl();
        $acl->deny();

        //gán quyền
        $acl->addRole(new Role('guest'));
        $acl->addRole(new Role('member',array('guest')));
        $acl->addRole(new Role('admin',array('member')));

        // thêm tài nguyên để phân quyền
        $acl->addResource('training')
            ->addResource('training:acl','training');

        //guest có thể vào index và deny
        $acl->allow('guest','training:acl',array('index','deny'));
        //member co them quyen add va edit. do member co quyen cua guest da dc them o gán quyền
        $acl->allow('member','training:acl',array('add','edit'));
        $acl->allow('admin');

        $route = $e->getRouteMatch();
        //lấy controller
        $controller = $route->getParam('controller');

//        $moduleName =strtolower(substr($controller,0,strpos($controller,'\\')));
        $arr = explode('\\',$controller);
        $controllerName = strtolower($arr[2]);
        $actionName = $route->getParam('action');
        $moduleName = strtolower($arr[0]);


        if(!$acl->isAllowed('admin',$moduleName.":".$controllerName,$actionName)){
            // nếu k hợp lệ
            return $this->redirect()->toRoute(null,array('controller' => 'acl','action'=>'deny'));
        }
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        echo "<h2> index Action </h2>";
        return false;
    }

    public function addAction()
    {
        echo "<h2> add Action </h2>";
        return false;
    }

    public function editAction()
    {
        echo "<h2> edit Action </h2>";
        return false;
    }

    public function deleteAction()
    {
        echo "<h2> delete Action </h2>";
        return false;
    }

    public function denyAction()
    {
        echo "<h2> deny Action </h2>";
        return false;
    }
}