<div class="row">
    <div class="col-md-4">
        <h3>Thêm tập tin</h3>
        <p>Vui lòng nhập tên</p>

        <?php
        $form = $this->form;
        $form->prepare();

        $form->setAttribute('action', $this->url('training/file', array('action' => 'add')));

        echo $this->form()->openTag($form);

        echo "<div class='form-group'>";
        echo $this->formLabel($form->get('label'));
        echo $this->formElement($form->get('label'));
        echo $this->formElementErrors($form->get('label'));
        echo "</div>";

        echo "<div class='form-group'>";
        echo $this->formLabel($form->get('file'));
        echo $this->formElement($form->get('file'));
        echo $this->formElementErrors($form->get('file'));
        echo "</div>";

        echo $this->formElement($form->get('submit'));
        echo $this->form()->closeTag();

        ?>
    </div>
</div>