<?php
/**
 * Created by PhpStorm.
 * User: Thai Duc
 * Date: 07-Mar-18
 * Time: 10:48 AM
 */

namespace Blog\Controller;


use Zend\Mvc\Controller\AbstractActionController;
use Zend\Mvc\MvcEvent;

class MainController extends AbstractActionController
{
    //gọi đầu tiên
    public function onDispatch(MvcEvent $e)
    {
        $route = $e->getRouteMatch();
        //lấy controller
        $controller = $route->getParam('controller');
        $arr = explode('\\', $controller);

        $moduleName = strtolower($arr[0]);

        $this->layout()->setTemplate('layout/'.$moduleName);
        return parent::onDispatch($e); // TODO: Change the autogenerated stub
    }
}