
<div class="row">
    <div class="col-md-6">
        <h3>Các sản phẩm trong giỏ của bạn</h3>

        <?php
        if(count($flash)){
            echo "<div class='alert alert-success'>";
            foreach ($flash as $mess){
                echo $mess;
            }
            echo "</div>";
        }
        ?>

        <?php
        $form->prepare();
        $form->setAttribute('action',$this->url('training/book',array('action' => 'updateItem')));
        $form->setAttribute('method','post');
        echo $this->form()->openTag($form);
        ?>
        <table class="table table-bordered table-responsive table-striped table-hover">
            <tr>
                <td>Tên sản phẩm</td>
                <td>Số lượng</td>
                <td>Giá</td>
                <td>Xoá</td>

            </tr>
            <?php
            if (!empty($cart)) {
                foreach ($cart as $token => $book) {
                    echo $this->formElement($form->get($book['id']."[token]"));
                    echo "<tr>";
                    echo " <td> $book[name]</td>";
                    echo " <td>".$this->formElement($form->get($book['id']."[qty]"))."</td>";
                    echo " <td>". $book['price']*$book['qty']."</td>";
                    echo " <td> <a href='".$this->url('training/book',array('action' => 'removeItem','id'=>$book['id']))."' class='btn btn-warning'>Xoá </a></td>";

                    echo "</tr>";
                }
                echo "<tr>";
                echo "<td colspan='2'> Tổng tiền </td>";
                echo "<td colspan='2'> ".$totalPriceInCart['sub-total'] ."</td>";
                echo "</tr>";
            } else {
                echo "<tr>";
                echo "<td colspan='5'> Không có sản phẩm trong giỏ </td>";
                echo "</tr>";
            }
            ?>
        </table>
        <?php

        echo $this->formElement($form->get('submit'));
        echo "&nbsp;<a href='".$this->url('training/book',array('action' => 'removeAll'))."' class='btn btn-danger'>Xoá tất cả </a>";
        echo "&nbsp;<a href='".$this->url('training/book',array('action' => 'checkout'))."' class='btn btn-success'> Thanh toán </a>";
        echo $this->form()->closeTag();
        ?>
    </div>
</div>