<?php
$this->headScript()->appendScript('
$("div.alert-success").delay(2000).slideUp();');
?>
<div class="row">
    <div class="col-md-9">
        <h2>Book shop</h2>
        <p><a href="<?php echo $this->url('training/book',array('action' => 'cart')) ?>">Giỏ hàng của bạn</a> / <b> Có <?php echo $this->totalProductInCart; ?> sản phẩm trong giỏ</b> / <a href="<?php echo $this->url('training/book',array('action' => 'historyPayment')) ?>">Lịch sử mua hàng</a> </p>

        <?php
        if(count($flash)){
            echo "<div class='alert alert-success'>";
            foreach ($flash as $mess){
                echo $mess;
            }
            echo "</div>";
        }
        ?>

        <?php
            $basePath = $this->basePath();
            foreach ($bookList as $book){
                echo "<div class='col-md-3'>";
                echo "<h4>$book->name </h4>";
                echo "<img src='$basePath/../$book->img' width='200' height='200'> ";
                echo "<p><b>Price: $book->price</b> </p>";
                echo "<a href='".$this->url('training/book', array('action' => 'addItem','id' => $book->id))."' class='btn btn-primary'>Thêm vào giỏ hàng </a>";
                echo "</div>";
            }
        ?>
    </div>
</div>